[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
num-complex = "0.4.4"
itertools = "0.10.0"  # Use the latest version available
bit-vec = "0.4.4"